name: 'att'
attributes:
    num_parallel_tunnels: 3  
    num_link_failures: 1
traffic_matrix:
    num_matrices: 1
    tm_index: 0
data: 
    cap_file: '../_data/att/att_capa.tab'
    tm_file: '../_data/att/att_traffic.tab'
    #tunnel_file: '../_data/att/att_ffc_tunnel.tab'
    #tunnel_file: '../_data/att/att_ls_tunnel.tab'
    tunnel_file: '../_data/att/att_cls_tunnel.tab'
