name: 'crlnetwork'
attributes:
    num_parallel_tunnels: 3  
    num_link_failures: 1
traffic_matrix:
    num_matrices: 1
    tm_index: 0
data: 
    cap_file: '../_data/crlnetwork/crlnetwork_capa.tab'
    tm_file: '../_data/crlnetwork/crlnetwork_traffic.tab'
    #tunnel_file: '../_data/crlnetwork/crlnetwork_ffc_tunnel.tab'
    #tunnel_file: '../_data/crlnetwork/crlnetwork_ls_tunnel.tab'
    tunnel_file: '../_data/crlnetwork/crlnetwork_cls_tunnel.tab'
