name: 'integra'
attributes:
    num_parallel_tunnels: 3  
    num_link_failures: 1
traffic_matrix:
    num_matrices: 1
    tm_index: 0
data: 
    cap_file: '../_data/integra/integra_capa.tab'
    tm_file: '../_data/integra/integra_traffic.tab'
    #tunnel_file: '../_data/integra/integra_ffc_tunnel.tab'
    #tunnel_file: '../_data/integra/integra_ls_tunnel.tab'
    tunnel_file: '../_data/integra/integra_cls_tunnel.tab'
