name: 'Ion'
attributes:
    num_parallel_tunnels: 3  
    num_link_failures: 1
traffic_matrix:
    num_matrices: 1
    tm_index: 0
data: 
    cap_file: '../_data/Ion/Ion_capa.tab'
    tm_file: '../_data/Ion/Ion_traffic.tab'
    #tunnel_file: '../_data/Ion/Ion_ffc_tunnel.tab'
    #tunnel_file: '../_data/Ion/Ion_ls_tunnel.tab'
    tunnel_file: '../_data/Ion/Ion_cls_tunnel.tab'
